services:
  frontend:
    image: country-tracker-frontend
    build:
      context: ./frontend
    ports:
      - "5030:80"  # Host (5030) maps to Container (80 - Nginx)
    depends_on:
      - backend

  backend:
    image: country-tracker-backend
    build:
      context: ./backend
    ports:
      - "5181:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
